// const data = {
//   users: [
//     {
//       name: "Christian",
//       lastName: "Chang",
//       cpf: "115.440.340-83",
//       nationality: "Brasileiro",
//       cep: "01011-100",
//       state: "SP",
//       city: "São Paulo",
//       street: "Rua Boa Vista",
//       email: "admin@example.com",
//       tel: "(11)2020-3030",
//     },
//     {
//       name: "Johnnhy",
//       lastName: "Depp",
//       cpf: "353.814.620-93",
//       nationality: "Americano",
//       cep: "01500-100",
//       state: "CA",
//       city: "Los Angeles",
//       street: "Santa Monica Boulevard",
//       email: "depp@example.com",
//       tel: "(11)2020-3030",
//     },
//     {
//       name: "Michael",
//       lastName: "Jordan",
//       cpf: "733.068.970-00",
//       nationality: "Americano",
//       cep: "01620-300",
//       state: "CA",
//       city: "Los Angeles",
//       street: "Santa Monica Boulevard",
//       email: "jordan@example.com",
//       tel: "(11)2020-3030",
//     },
//     {
//       name: "Neymar",
//       lastName: "Junior",
//       cpf: "363.067.360-00",
//       nationality: "Brasileiro",
//       cep: "04500-100",
//       state: "SP",
//       city: "Santos",
//       street: "Rua Julia Santos Paiva",
//       email: "n10@example.com",
//       tel: "(11)2020-3030",
//     },
//   ],
// };

// export default data;
